// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'
export const FETCH_GETUSERS_SUCCESS = 'FETCH_GETUSERS_SUCCESS'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// project.js
export const SAVE_PROJECT_LIST = "SAVE_PROJECT_LIST"
export const LOAD_PROJECT = "LOAD_PROJECT"
export const SAVE_PROJECT_TYPE = "SAVE_PROJECT_TYPE"
export const SAVE_SEP = "SAVE_SEP"
export const SAVE_DRY_GAS = "SAVE_DRY_GAS"
export const SAVE_SURFACE = "SAVE_SURFACE"
export const SAVE_RESERVOIR = "SAVE_RESERVOIR"
export const SAVE_WELLHISTORY = "SAVE_WELLHISTORY"
export const SAVE_ECONOMICS = "SAVE_ECONOMICS"
export const SAVE_OPERATIONS = "SAVE_OPERATIONS"
export const SAVE_GAS_CONDENSATE = "SAVE_GAS_CONDENSATE"
export const SAVE_REL_PERM = "SAVE_REL_PERM"
export const UPDATE_RES_KGKO = "UPDATE_RES_KGKO"

export const SAVE_RES_KGKO = "SAVE_RES_KGKO"
export const SAVE_RES_CVDOUT = "SAVE_RES_CVDOUT"
export const SAVE_RES_OPTIMIZER = "SAVE_RES_OPTIMIZER"
export const SAVE_RES_FASTPLAN = "SAVE_RES_FASTPLAN"
export const SAVE_RES_MONITORING = "SAVE_RES_MONITORING"

export const FETCH_LICENSES_SUCCESS = 'FETCH_LICENSES_SUCCESS'
